# Generated by Django 6.0.1 on 2026-01-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hotel',
            name='hotels_hote_categor_c1dbd8_idx',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
